name: EC2 CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout files
        uses: actions/checkout@v2

      - name: Add EC2 to SSH known hosts
        env:
          EC2_HOST_KEY: ${{ secrets.EC2_HOST_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_HOST_KEY }}" >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          HOST_DNS: ${{ secrets.HOST_DNS }}
          USERNAME: ${{ secrets.USERNAME }}
          TARGET_DIR: ${{ secrets.TARGET_DIR }}
        run: |
          echo "$EC2_SSH_KEY" > private_key.pem
          chmod 600 private_key.pem
          ssh -i private_key.pem $USERNAME@$HOST_DNS 'sudo yum update -y && sudo rm -rf $TARGET_DIR && git clone https://github.com/Rohit-kamath/461-G12-P2.git $TARGET_DIR'
          rm -f private_key.pem

